{
    "openapi": "3.0.2",
    "info": {
        "title": "games-api",
        "version": "1.0.0",
        "description": ""
    },
    "paths": {
        "/games": {
            "get": {
                "tags": [
                    "games"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {}
                                },
                                "examples": {
                                    "List of games": {
                                        "value": [
                                            "Witcher 3",
                                            "Cyberpunk 2077",
                                            "Red Dead Redemption 2",
                                            "Elden Ring"
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "Returns full details of a given id game"
                    }
                },
                "summary": "Get a list of all games",
                "description": "Returns a list of all games in API"
            }
        },
        "/games/{id}": {
            "get": {
                "tags": [
                    "details"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {}
                        },
                        "description": "Returns full details of a given id game"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Game /w+ was not found": {
                                        "value": {
                                            "error": "Game \\w+ was not found in game array."
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Game was not found in games array"
                    }
                },
                "operationId": "id",
                "summary": "Get full details of a game",
                "description": "Returns full details of a given id game\n"
            }
        }
    },
    "components": {
        "schemas": {
            "error": {
                "title": "Root Type for error",
                "description": "",
                "type": "object",
                "properties": {
                    "error": {
                        "type": "string"
                    }
                },
                "example": {
                    "error": "Error message."
                }
            }
        }
    }
}